### ISSUE TITLE
Tasseled Cap Transformations

### ISSUE THREAD

**Issue by aazuspan** [r-earthengine/ee_extra#5]
See the original feature request on [eemont](https://github.com/davemlz/eemont/issues/46).

This would add an `ee_extra.Transformations` module with a `tasseledCap` function to calculate [tasseled cap](https://en.wikipedia.org/wiki/Tasseled_cap_transformation) brightness, wetness, and greenness bands from an input `ee.Image` from the MODIS, Landsat 5/7/8, or Sentinel-2 platforms. 

A couple design questions:

- Should the tasseled cap bands be added to the original image (like `spectralIndices`) or returned as a new `ee.Image`?
- How strict should the platform matching be? For example, published [Landsat 8 coefficients](https://www.tandfonline.com/doi/abs/10.1080/2150704X.2014.915434?journalCode=trsl20) were generated for at-sensor reflectance and *technically* aren't accurate for TOA or Surface Reflectance (see the warning on [Hexagon Geospatial](https://geospatialcommunity.hexagon.com/s/article/Tasseled-Cap-Transformation-for-Landsat-8)). Should that be strictly enforced or just mentioned in the docs?

Feel free to assign me, thanks!

**Comment by davemlz** [comment]
Awesome to see you here, @aazuspan! :confetti_ball: 

I was thinking. We have a `Spectral` module here in `eeExtra` related to the spectral indices computation (`ee_extra.Spectral`). If you want, you can add it there :)

Regarding the design questions:
1. Yes, adding them to the original image is nice since users won't need to deal with a lot of variables :)
2. I think that they meant TOA when the said "at-sensor", but I could be wrong, I just checked the paper and they say that they computed reflectance according to this [USGS](https://www.usgs.gov/core-science-systems/nli/landsat/using-usgs-landsat-level-1-data-product) page, and it is the TOA reflectance. I know that it shouldn't vary too much if we allow people to use Surface Reflectance, but we have no reference for that :( so I think it is better if we are strict here :)

I'll assign you this Issue then, @aazuspan! If you need something, please let us know! :) :rocket:

**Comment by aazuspan** [comment]
Adding `tasseledCap` to the `Spectral` module makes sense to me!

I'm not super familiar with the different levels of Landsat processing, but I did see that the GEE catalog describes the [Landsat raw datasets](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LO08_C01_T1#description) as at-sensor

> Landsat 8 Collection 1 Tier 1 OLI DN values, representing scaled, calibrated at-sensor radiance.

I'll do a little more research and also see if I can track down coefficients for surface reflectance data :)

Thanks @davemlz!

**Comment by davemlz** [comment]
I found this [example](https://developers.google.com/earth-engine/guides/arrays_array_images?hl=en) in the EE Guide that uses TOA but for L5. But for L8 I'm not sure. I have never used tasseled cap xD I would say that if in the paper they say that they used DN, let's use the RAW values, and if they say that they used Reflectance, let's use the TOA values (unless SR is explicitly mentioned) :)

If you find references, it would be nice to add them to the docstrings! :rocket: Here an example:

```python
def tasseledCap(x: Union[ee.Image, ee.ImageCollection]) -> Union[ee.Image, ee.ImageCollection]:
    """Computes the Tasseled Cap Transformation [1]_.

    Args:
        x : Image or Image Collection, etc.

    Returns:
        Image or Image Collection, etc.

    References:
        .. [1] `Doe, John. 2021. Tasseled Cap Transformations, etc. <https://link.com/>`_
    """
    return None
```

If you have troubles or questions, let us know! :)

Thank you, @aazuspan!

**Comment by aazuspan** [comment]
Sounds like a good plan, thanks for looking into it! :)
